name: "Build Daemon"
description: "Build wgmd-aarch64"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Install cross
      run: cargo install cross
    - name: Build
      working-directory: wgmd
      run: cross build --release --target aarch64-unknown-linux-gnu
    - uses: actions/upload-artifact@v4
      with:
        name: wgmd-aarch64
        path: wgmd/target/aarch64-unknown-linux-gnu/release/wgmd