[package]
name = "wgmd"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = "3.5.2"
ipnet = "2.12.1"
rusqlite = { version = "0.40.1", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
ts-rs = "12.0.1"
users = "0.11.0"
uuid = { version = "1.24.0", features = ["v4"] }
