[Interface]
Address = 172.31.0.1/16
#ListenPort = 51820
ListenPort = 42069
PrivateKey = eOVCP8JlSTp+DpWsm4o24Um7tf7yNg//XvWm9Az7fUk=
MTU = 1420
Table = off
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# rillo
[Peer]
PublicKey = d5Eyc7x6P2mZMSHANn1SWN3fj9AhHrZBto1wUEyODx4=
PresharedKey = FqQyYBAq4d+o1UNsvgdPNmtGEFL63yr4+1QWTxOGMPA=
AllowedIPs = 172.31.1.0/24, 172.31.0.2/32, 172.31.0.4, 172.31.0.5
# subnet, macmini, iphone, macbook

# lobotomy
[Peer]
PublicKey = 3jpOWuiqMSTSxzZFYP9KcgVSIDTPRGPexhgH0pbDAQU=
PresharedKey = w9i0JZ42qedHm5WF/1zvGKfKzhB4E5rJgxxPCPuU4Ck=
AllowedIPs = 172.31.2.0/24, 172.31.0.3/32
